name: CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # TypeScript only if tsconfig.json exists
      - if: hashFiles('tsconfig.json') != ''
        run: npx tsc --noEmit

      # ESLint only if any eslint config exists
      - if: |
          hashFiles('.eslintrc*') != '' ||
          hashFiles('**/.eslintrc*') != ''
        run: npx eslint . --max-warnings=0

      # Non-interactive Expo health check
      - run: npx expo doctor --fix --ci
